# 1. Configuração da Porta para o Nginx Gateway achar o Finance
server.port=3003

# 2. Configuração da Base de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/financedb
spring.datasource.username=facoffee
# ATENÇÃO: Ajustado para bater exatamente com a senha que colocamos no docker-compose
spring.datasource.password=facoffee
spring.datasource.driver-class-name=org.postgresql.Driver

# 3. Configurações do Hibernate / JPA para Postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# CONFIGURAÇÕES DO KAFKA
spring.kafka.bootstrap-servers=localhost:9092

# Configurações do Consumidor (Consumer)
spring.kafka.consumer.group-id=finance-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=ufms.facoffe.finance.dto.events

# Configurações do Produtor (Producer)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# SECRET DO JWT (Deve bater com a chave do Keycloak/Gateway do projeto)
app.security.jwt.secret=sua_chave_secreta_super_segura_com_mais_de_32_caracteres